/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.DefaultSchema;
import ru.tinkoff.edu.java.scrapper.domain.jooq.Keys;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.LinksListRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinksList extends TableImpl<LinksListRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LINKS_LIST</code>
     */
    public static final LinksList LINKS_LIST = new LinksList();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<LinksListRecord> getRecordType() {
        return LinksListRecord.class;
    }

    /**
     * The column <code>LINKS_LIST.TRACK_ID</code>.
     */
    public final TableField<LinksListRecord, Long> TRACK_ID = createField(DSL.name("TRACK_ID"),
        SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>LINKS_LIST.LINK_ID</code>.
     */
    public final TableField<LinksListRecord, Long> LINK_ID = createField(DSL.name("LINK_ID"),
        SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>LINKS_LIST.TG_CHAT</code>.
     */
    public final TableField<LinksListRecord, Long> TG_CHAT = createField(DSL.name("TG_CHAT"),
        SQLDataType.BIGINT.nullable(false), this, "");

    private LinksList(Name alias, Table<LinksListRecord> aliased) {
        this(alias, aliased, null);
    }

    private LinksList(Name alias, Table<LinksListRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LINKS_LIST</code> table reference
     */
    public LinksList(String alias) {
        this(DSL.name(alias), LINKS_LIST);
    }

    /**
     * Create an aliased <code>LINKS_LIST</code> table reference
     */
    public LinksList(Name alias) {
        this(alias, LINKS_LIST);
    }

    /**
     * Create a <code>LINKS_LIST</code> table reference
     */
    public LinksList() {
        this(DSL.name("LINKS_LIST"), null);
    }

    public <O extends Record> LinksList(Table<O> child, ForeignKey<O, LinksListRecord> key) {
        super(child, key, LINKS_LIST);
    }

    @Override
    @NotNull
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<LinksListRecord, Long> getIdentity() {
        return (Identity<LinksListRecord, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<LinksListRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_8;
    }

    @Override
    @NotNull
    public List<UniqueKey<LinksListRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UN_TRACK);
    }

    @Override
    @NotNull
    public List<ForeignKey<LinksListRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_86, Keys.CONSTRAINT_866);
    }

    private transient Links _links;
    private transient Chats _chats;

    /**
     * Get the implicit join path to the <code>PUBLIC.LINKS</code> table.
     */
    public Links links() {
        if (_links == null)
            _links = new Links(this, Keys.CONSTRAINT_86);

        return _links;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.CHATS</code> table.
     */
    public Chats chats() {
        if (_chats == null)
            _chats = new Chats(this, Keys.CONSTRAINT_866);

        return _chats;
    }

    @Override
    @NotNull
    public LinksList as(String alias) {
        return new LinksList(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public LinksList as(Name alias) {
        return new LinksList(alias, this);
    }

    @Override
    @NotNull
    public LinksList as(Table<?> alias) {
        return new LinksList(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinksList rename(String name) {
        return new LinksList(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinksList rename(Name name) {
        return new LinksList(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinksList rename(Table<?> name) {
        return new LinksList(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super Long,
        ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
