version: '2'

services:

  postgres:
    image: 'postgres:15.2-alpine'
    container_name: postgres
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=scrapperDB
    restart: always
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgres
    command:
      - --hub-mode=off
      - --changelog-file=master.yaml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgres:5432/scrapperDB
      - --username=admin
      - --password=0000
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

networks:
  backend: {}