scrape_configs:
    -   job_name: 'bot_metics'
        scrape_interval: 5s
        metrics_path: '/metrics'
        static_configs:
            - targets: ['host.docker.internal:8081']

    -   job_name: 'scrapper_metics'
        scrape_interval: 5s
        metrics_path: '/metrics'
        static_configs:
            -   targets: ['host.docker.internal:8182']
