/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;


import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Chats;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatsRecord extends UpdatableRecordImpl<ChatsRecord> implements Record1<Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CHATS.TG_CHAT</code>.
     */
    public void setTgChat(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>CHATS.TG_CHAT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getTgChat() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row1<Long> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Chats.CHATS.TG_CHAT;
    }

    @Override
    @NotNull
    public Long component1() {
        return getTgChat();
    }

    @Override
    @NotNull
    public Long value1() {
        return getTgChat();
    }

    @Override
    @NotNull
    public ChatsRecord value1(@NotNull Long value) {
        setTgChat(value);
        return this;
    }

    @Override
    @NotNull
    public ChatsRecord values(@NotNull Long value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatsRecord
     */
    public ChatsRecord() {
        super(Chats.CHATS);
    }

    /**
     * Create a detached, initialised ChatsRecord
     */
    @ConstructorProperties({ "tgChat" })
    public ChatsRecord(@NotNull Long tgChat) {
        super(Chats.CHATS);

        setTgChat(tgChat);
    }

    /**
     * Create a detached, initialised ChatsRecord
     */
    public ChatsRecord(ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos.Chats value) {
        super(Chats.CHATS);

        if (value != null) {
            setTgChat(value.getTgChat());
        }
    }
}
