/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;


import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.LinksList;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinksListRecord extends UpdatableRecordImpl<LinksListRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINKS_LIST.TRACK_ID</code>.
     */
    public void setTrackId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINKS_LIST.TRACK_ID</code>.
     */
    @NotNull
    public Long getTrackId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LINKS_LIST.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINKS_LIST.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>LINKS_LIST.TG_CHAT</code>.
     */
    public void setTgChat(@NotNull Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>LINKS_LIST.TG_CHAT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getTgChat() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return LinksList.LINKS_LIST.TRACK_ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return LinksList.LINKS_LIST.LINK_ID;
    }

    @Override
    @NotNull
    public Field<Long> field3() {
        return LinksList.LINKS_LIST.TG_CHAT;
    }

    @Override
    @NotNull
    public Long component1() {
        return getTrackId();
    }

    @Override
    @NotNull
    public Long component2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Long component3() {
        return getTgChat();
    }

    @Override
    @NotNull
    public Long value1() {
        return getTrackId();
    }

    @Override
    @NotNull
    public Long value2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Long value3() {
        return getTgChat();
    }

    @Override
    @NotNull
    public LinksListRecord value1(@NotNull Long value) {
        setTrackId(value);
        return this;
    }

    @Override
    @NotNull
    public LinksListRecord value2(@NotNull Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public LinksListRecord value3(@NotNull Long value) {
        setTgChat(value);
        return this;
    }

    @Override
    @NotNull
    public LinksListRecord values(@NotNull Long value1, @NotNull Long value2, @NotNull Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinksListRecord
     */
    public LinksListRecord() {
        super(LinksList.LINKS_LIST);
    }

    /**
     * Create a detached, initialised LinksListRecord
     */
    @ConstructorProperties({ "trackId", "linkId", "tgChat" })
    public LinksListRecord(@NotNull Long trackId, @NotNull Long linkId, @NotNull Long tgChat) {
        super(LinksList.LINKS_LIST);

        setTrackId(trackId);
        setLinkId(linkId);
        setTgChat(tgChat);
    }

    /**
     * Create a detached, initialised LinksListRecord
     */
    public LinksListRecord(ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos.LinksList value) {
        super(LinksList.LINKS_LIST);

        if (value != null) {
            setTrackId(value.getTrackId());
            setLinkId(value.getLinkId());
            setTgChat(value.getTgChat());
        }
    }
}
