app:
  test: hi
  scheduler:
    interval: 5000

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs

server:
  port: 8181

spring:
  application:
    name: test

  datasource:
    url: jdbc:postgresql://postgres:5432/scrapper
    username: arina
    password: 0000
    driver-class-name: org.postgresql.Driver





