app:
  test: hi
  scheduler:
    interval: 5000
  database-access-type: jpa
  queue: qScrapper
  exchange: exScrapper
  useQueue: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs

server:
  port: 8181

spring:
  application:
    name: scrapperApp
  jpa:
    hibernate:
      ddl-auto: update
      format-sql: true
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5433/scrapper
    username: arina
    driver-class-name: org.postgresql.Driver
    password: "0000"


github:
  token: ${GITHUB_TOKEN}

management:
    metrics:
        tags:
            application: ${spring.application.name}
    server:
        port: 8182
    endpoints:
        web:
            base-path: /
            path-mapping:
                prometheus: metrics
            exposure:
                include: "*"
        enabled-by-default: false

    endpoint:
        info:
            enabled: true
        health:
            enabled: true
        metrics:
            enabled: true
        prometheus:
            enabled: true
    prometheus:
        metrics:
            export:
                enabled: true
