/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chats implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long tgChat;

    public Chats() {}

    public Chats(Chats value) {
        this.tgChat = value.tgChat;
    }

    @ConstructorProperties({ "tgChat" })
    public Chats(
        @NotNull Long tgChat
    ) {
        this.tgChat = tgChat;
    }

    /**
     * Getter for <code>CHATS.TG_CHAT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getTgChat() {
        return this.tgChat;
    }

    /**
     * Setter for <code>CHATS.TG_CHAT</code>.
     */
    public void setTgChat(@NotNull Long tgChat) {
        this.tgChat = tgChat;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Chats other = (Chats) obj;
        if (this.tgChat == null) {
            if (other.tgChat != null)
                return false;
        }
        else if (!this.tgChat.equals(other.tgChat))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.tgChat == null) ? 0 : this.tgChat.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Chats (");

        sb.append(tgChat);

        sb.append(")");
        return sb.toString();
    }
}
