/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Links implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long linkId;
    private String link;
    private LocalDateTime lastChecked;

    public Links() {}

    public Links(Links value) {
        this.linkId = value.linkId;
        this.link = value.link;
        this.lastChecked = value.lastChecked;
    }

    @ConstructorProperties({ "linkId", "link", "lastChecked" })
    public Links(
        @NotNull Long linkId,
        @NotNull String link,
        @NotNull LocalDateTime lastChecked
    ) {
        this.linkId = linkId;
        this.link = link;
        this.lastChecked = lastChecked;
    }

    /**
     * Getter for <code>LINKS.LINK_ID</code>.
     */
    @NotNull
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>LINKS.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>LINKS.LINK</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 255)
    @NotNull
    public String getLink() {
        return this.link;
    }

    /**
     * Setter for <code>LINKS.LINK</code>.
     */
    public void setLink(@NotNull String link) {
        this.link = link;
    }

    /**
     * Getter for <code>LINKS.LAST_CHECKED</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public LocalDateTime getLastChecked() {
        return this.lastChecked;
    }

    /**
     * Setter for <code>LINKS.LAST_CHECKED</code>.
     */
    public void setLastChecked(@NotNull LocalDateTime lastChecked) {
        this.lastChecked = lastChecked;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Links other = (Links) obj;
        if (this.linkId == null) {
            if (other.linkId != null)
                return false;
        }
        else if (!this.linkId.equals(other.linkId))
            return false;
        if (this.link == null) {
            if (other.link != null)
                return false;
        }
        else if (!this.link.equals(other.link))
            return false;
        if (this.lastChecked == null) {
            if (other.lastChecked != null)
                return false;
        }
        else if (!this.lastChecked.equals(other.lastChecked))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.link == null) ? 0 : this.link.hashCode());
        result = prime * result + ((this.lastChecked == null) ? 0 : this.lastChecked.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Links (");

        sb.append(linkId);
        sb.append(", ").append(link);
        sb.append(", ").append(lastChecked);

        sb.append(")");
        return sb.toString();
    }
}
