/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinksList implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long trackId;
    private Long linkId;
    private Long tgChat;

    public LinksList() {}

    public LinksList(LinksList value) {
        this.trackId = value.trackId;
        this.linkId = value.linkId;
        this.tgChat = value.tgChat;
    }

    @ConstructorProperties({ "trackId", "linkId", "tgChat" })
    public LinksList(
        @NotNull Long trackId,
        @NotNull Long linkId,
        @NotNull Long tgChat
    ) {
        this.trackId = trackId;
        this.linkId = linkId;
        this.tgChat = tgChat;
    }

    /**
     * Getter for <code>LINKS_LIST.TRACK_ID</code>.
     */
    @NotNull
    public Long getTrackId() {
        return this.trackId;
    }

    /**
     * Setter for <code>LINKS_LIST.TRACK_ID</code>.
     */
    public void setTrackId(@NotNull Long trackId) {
        this.trackId = trackId;
    }

    /**
     * Getter for <code>LINKS_LIST.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>LINKS_LIST.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>LINKS_LIST.TG_CHAT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getTgChat() {
        return this.tgChat;
    }

    /**
     * Setter for <code>LINKS_LIST.TG_CHAT</code>.
     */
    public void setTgChat(@NotNull Long tgChat) {
        this.tgChat = tgChat;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final LinksList other = (LinksList) obj;
        if (this.trackId == null) {
            if (other.trackId != null)
                return false;
        }
        else if (!this.trackId.equals(other.trackId))
            return false;
        if (this.linkId == null) {
            if (other.linkId != null)
                return false;
        }
        else if (!this.linkId.equals(other.linkId))
            return false;
        if (this.tgChat == null) {
            if (other.tgChat != null)
                return false;
        }
        else if (!this.tgChat.equals(other.tgChat))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.trackId == null) ? 0 : this.trackId.hashCode());
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.tgChat == null) ? 0 : this.tgChat.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LinksList (");

        sb.append(trackId);
        sb.append(", ").append(linkId);
        sb.append(", ").append(tgChat);

        sb.append(")");
        return sb.toString();
    }
}
