app-bot:
  test: hi
  queue: qScrapper
  exchange: exScrapper



springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs

server:
  port: 8081

spring:
  application:
    name: test
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false

telegram:
  bot-name: ${BOT_NAME}
  bot-token: ${BOT_TOKEN}
  api-url: "https://api.telegram.org/"