name: Build bot

on:
  push:
    paths:
      - 'bot/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bot
  AUTHOR: eliorika

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build bot
        run: mvn package -pl bot -am

      - name: Build Docker image
        run: docker build -f bot.dockerfile -t ${{ env.REGISTRY}}/${{ env.AUTHOR }}/${{ env.IMAGE_NAME }}:latest .

      - name: Log in to the Container registry
          uses: docker/login-action@v1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
