name: Build bot

on:
  push:
    paths:
      - 'bot/**'

environment:
  REGISTRY: ghcr.io
  IMAGE_NAME: bot
  AUTHOR: eliorika

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build bot
        run: mvn package -pl bot -am

      - name: Build Docker image
        run: docker build -f bot.dockerfile -t ${{ environment.REGISTRY}}/${{ environment.AUTHOR }}/${{ environment.IMAGE_NAME }}:latest .
